# Generated by Django 5.2.4 on 2025-07-14 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emial',
            new_name='email',
        ),
    ]
