# Generated by Django 5.2.4 on 2025-08-01 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cyear', models.IntegerField()),
                ('compnaychoice', models.CharField(choices=[('Maruti', 'Maruti'), ('Mahindra', 'Mahindra'), ('Hyundai', 'Hyundai')], max_length=120)),
                ('cname', models.CharField(max_length=120)),
                ('cprice', models.IntegerField()),
                ('cimage', models.ImageField(default='', upload_to='car/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
