# Generated by Django 5.2.4 on 2025-08-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.IntegerField(default='petrol'),
        ),
        migrations.AddField(
            model_name='car',
            name='luggage',
            field=models.IntegerField(default='2'),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(default='4000'),
        ),
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.IntegerField(default='4'),
        ),
    ]
