# Generated by Django 5.2.4 on 2025-08-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_car_fuel_car_luggage_car_mileage_car_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(default='petrol'),
        ),
    ]
