# Generated by Django 5.2.4 on 2025-08-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_car_fuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(default='petrol', max_length=100),
        ),
    ]
